remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"

title: ReplayWeb.Page

# Enable or disable the site search
search_enabled: false

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Back to ReplayWeb.page":
    - "https://replayweb.page/"

logo: "/assets/logo.svg"

plugins:
  - jekyll-remote-theme

